# Rounding (matches decoration:rounding = 10)
rounding_large = 10
rounding_small = 5

# Colors (defaults, to be themed later)
background      = 0xFF181818
base            = 0xFF202020
text            = 0xFFDADADA
alternate_base  = 0xFF272727
bright_text     = 0xFFFFDEDE
accent          = 0xFF00FFCC
accent_secondary = 0xFF0099F0

# Font sizes
h1_size         = 19
h2_size         = 15
h3_size         = 13
font_size       = 11
small_font_size = 10

# Fonts / icons
font_family           = Sans Serif
font_family_monospace = monospace
icon_theme            =
