# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

source = $HOME/.cache/wal/colors-hyprland.conf

$font = Monospace

general {
    hide_cursor = false
    ignore_empty_input = true
    fail_timeout = 1000
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor = eDP-1
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $color2 $color13 45deg
    check_color = $color13 $color2 120deg
    fail_color = $color1 $color1 40deg

    font_color = rgb(183, 183, 183)
    fade_on_empty = false
    fade_timeout = 4000
    rounding = 10

    font_family = $font

    placeholder_text = $FPRINTPROMPT
    check_text = Authenticating...
    fail_text = Authentication Failed, $ATTEMPTS[]

    dots_spacing = 0.3

    position = 0,-75
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 100
    font_family = $font
    color = rgb(220, 220, 220)

    position = 0,40
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%a, %d %b" # update every 60 seconds
    font_size = 25
    font_family = $font
    color = $color13

    position = 0, 125
    halign = center
    valign = center
}
