# Catppuccin Macchiato Flavor
# Theme create by: https://github.com/GV14982
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= Border =========
file_panel_border = "{color8}" # Overlay0
sidebar_border = "{color8}"    # Base
footer_border = "{color8}"     # Overlay0

# ========= Border Active =========
file_panel_border_active = "{color6}" # Lavendar
sidebar_border_active = "{color1}"    # Red
footer_border_active = "{color2}"     # Green
modal_border_active = "{color7}"      # Overlay2

# ========= Background (bg) =========
full_screen_bg = "{color0}" # Base
file_panel_bg = "{color0}"  # Base
sidebar_bg = "{color0}"     # Base
footer_bg = "{color0}"      # Base
modal_bg = "{color0}"       # Base

# ========= Foreground (fg) =========
full_screen_fg = "{color7}" # Subtext0
file_panel_fg = "{color7}"  # Subtext0
sidebar_fg = "{color7}"     # Subtext0
footer_fg = "{color7}"      # Subtext0
modal_fg = "{color7}"       # Subtext0

# ========= Special Color =========
cursor = "{color5}"  # Rosewater
correct = "{color2}" # Green
error = "{color1}"   # Red
hint = "{color6}"    # Sapphire
cancel = "{color5}"  # Maroon
# Gradient color can only have two color!
gradient_color = ["{color4}", "{color5}"] # [Blue, Mauve]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "{color2}" # Green
file_panel_top_path = "{color4}"           # Blue
file_panel_item_selected_fg = "{color6}"   # Sky
file_panel_item_selected_bg = "{color0}"   # Base

# ========= Sidebar Special Items =========
sidebar_title = "{color6}"            # Sapphire
sidebar_item_selected_fg = "{color6}" # Sky
sidebar_item_selected_bg = "{color0}" # Base
sidebar_divider = "{color15}"          # Overlay2

# ========= Modal Special Items =========
modal_cancel_fg = "{color8}" # Surface0
modal_cancel_bg = "{color5}" # Maroon

modal_confirm_fg = "{color8}" # Surface0
modal_confirm_bg = "{color6}" # Sky

# ========= Help Menu =========
help_menu_hotkey = "{color6}" # Sky
help_menu_title = "{color5}"  # Maroon
