gestures {
    gesture = 3, horizontal, workspace
    gesture = 3, up, fullscreen
    gesture = 3, down, fullscreen
    gesture = 2, pinchout, move
    gesture = 2, pinchin, resize
    gesture = 4, swipe, dispatcher, exec, swaylock
}
